-- AlterTable
ALTER TABLE "Quote" ADD COLUMN     "additionalHourlyRate" DECIMAL(10,2) NOT NULL DEFAULT 150,
ADD COLUMN     "reportRate" DECIMAL(10,2) NOT NULL DEFAULT 350,
ADD COLUMN     "siteVisitRate" DECIMAL(10,2) NOT NULL DEFAULT 150;
